title: Home automation adventures
email: ivancea96@outlook.com
description: Guía, consejos e historias sobre la automatización del hogar u oficina
url: "https://ivancea.github.io/home-automation-adventures"
repository: ivancea/home-automation-adventures
twitter_username: ivancea96
github_username:  ivancea
github:
  is_project_page: false

data_dir: CV